site_name: AutoDocs MCP Server
site_description: Intelligent documentation context provider for AI assistants
site_author: Bradley Fay
site_url: https://bradleyfay.github.io/autodoc-mcp/
repo_url: https://github.com/bradleyfay/autodoc-mcp
repo_name: bradleyfay/autodoc-mcp
edit_uri: edit/main/docs/
strict: false

nav:
  - Home: index.md
  - 🚀 Getting Started:
    - Quick Setup: product/getting-started.md
    - Installation: product/installation.md
    - First API Call: product/first-api-call.md
  - 📚 Documentation:
    - product/index.md
    - MCP Tools: product/mcp-tools.md
    - Configuration: product/configuration.md
    - API Reference: product/api-reference.md
    - Troubleshooting: product/troubleshooting.md
  - 🏗️ Development:
    - development/index.md
    - Architecture: development/architecture.md
    - Contributing: development/contributing.md
    - Testing Strategy: development/testing.md
    - Standards: development/standards.md
    - Technical Decisions: development/technical-decisions.md
  - 🤖 Claude Code Agents:
    - agents/index.md
    - Claude Agent Builder: agents/claude-agent-builder.md
  - 📖 Project Journey:
    - journey/index.md
    - Project Evolution: journey/evolution.md
    - Phase Completions:
      - journey/phases/phase-1-core-validation.md
      - journey/phases/phase-2-documentation-fetching.md
      - journey/phases/phase-3-network-resilience.md
      - journey/phases/phase-4-dependency-context.md
    - Technical Learnings: journey/learnings.md
    - Development Sessions: journey/sessions.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - git-committers:
      repository: bradleyfay/autodoc-mcp
      branch: main
      enabled: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - abbr
  - def_list
  - toc:
      permalink: true
  - pymdownx.emoji

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bradleyfay/autodoc-mcp
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/autodoc-mcp/

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 Bradley Fay - <a href="#__consent">Change cookie settings</a>
