name: Claude Code Integration

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read

jobs:
  claude:
    if: contains(github.event.comment.body, '@claude') && (github.event.issue.pull_request || github.event.pull_request)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Allow additional tools for AutoDocs MCP development
          allowed_tools: |
            Bash(uv:*),
            Bash(pytest:*),
            Bash(python -m:*),
            Bash(git:*),
            Bash(gh:*),
            Bash(ruff:*),
            Bash(mypy:*)
