name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  claude-review:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Claude Code Review
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Please review this pull request focusing on:
            1. Code quality and best practices
            2. Test coverage for new functionality
            3. Documentation completeness
            4. Potential bugs or edge cases
            5. Performance implications
            6. Security considerations

            For the AutoDocs MCP Server project, pay special attention to:
            - MCP protocol compliance
            - Async/await patterns
            - Error handling and graceful degradation
            - Cache management
            - PyPI API integration
            - Test reliability and mocking patterns

            Provide constructive feedback and suggestions for improvement.
          allowed_tools: |
            Bash(uv run pytest:*),
            Bash(uv run ruff:*),
            Bash(uv run mypy:*)
